# Generated by Django 3.2 on 2021-05-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='photo',
        ),
        migrations.AddField(
            model_name='star',
            name='image',
            field=models.ImageField(default='media/stars/photo/7.png', upload_to='stars/image/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='savedmovie',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
